export const UI_TEXT = {
  appName: "Stock Analysis",
  nav: {
    home: "Trang chủ",
    market: "Thị trường",
    watchlist: "Theo dõi",
    trade: "Giao dịch",
    autoTrading: "Auto Trading",
    operations: "Giám sát vận hành",
  },
  home: {
    title: "Bảng điều khiển phân tích cổ phiếu",
    description:
      "Giao diện kết nối backend VNStock: danh sách mã, chi tiết mã, biểu đồ và giao dịch.",
    openMarket: "Mở thị trường",
    openTrade: "Mở giao dịch",
    openAutoTrading: "Mở Auto Trading",
    badge: "SÀN CHỨNG KHOÁN",
    news: {
      badge: "TIN TỨC",
      title: "Tin tức",
      description:
        "Tổng hợp từ RSS và nguồn công khai (theo nhóm: trong nước, thế giới, mạng xã hội).",
      filterAll: "Tất cả",
      filterDomestic: "Trong nước",
      filterWorld: "Thế giới",
      filterSocial: "Mạng xã hội",
      filtersAria: "Lọc danh mục tin",
      refresh: "Làm mới",
      refreshAria: "Làm mới tin, bỏ qua cache server",
      refreshLoading: "Đang làm mới...",
      loading: "Đang tải tin...",
      empty: "Chưa có tin cho bộ lọc này.",
      resultCount: (count: number) => `${count} bài`,
    },
  },
  market: {
    title: "Danh sách mã cổ phiếu",
    loadFailed: "Không tải được dữ liệu thị trường",
    refreshFromServer: "Làm mới",
    refreshFromServerLoading: "Đang làm mới...",
    refreshFromServerFailed: "Không làm mới được danh sách.",
    searchPlaceholder: "Tìm mã hoặc ngành",
    sortAz: "Sắp xếp: Mã A-Z",
    sortZa: "Sắp xếp: Mã Z-A",
    result: (count: number) => `Kết quả: ${count} mã`,
    showing: (from: number, to: number) => `Hiển thị ${from}-${to}`,
    searching: "Đang tìm...",
    prev: "Trước",
    next: "Sau",
    page: (current: number, total: number) => `Trang ${current} / ${total}`,
    exchangeAll: "ALL (Tất cả)",
    vn30ListLoading: "Đang tải danh sách VN30...",
    vn30ListError: "Không tải được danh sách VN30. Vẫn có thể lọc theo sàn HOSE / HNX / UPCOM.",
    scanner: {
      title: "Scanner thanh khoản đột biến bất thường",
      daysLabel: "Số ngày",
      asOfPrefix: "Cập nhật:",
      modeLabel: "Chế độ:",
      modeNormal: "Thường",
      modeAi: "AI",
      scanNow: "Quét",
      scanWithAi: "Quét bằng AI",
      scanning: "Đang quét...",
      scanningMarket: "Đang quét thị trường...",
      riskPrefix: "Rủi ro:",
      spikeLine: (ratio: string, latest: string, base: string) =>
        `Tỷ lệ đột biến: ${ratio}x | KL gần nhất: ${latest} | KL nền: ${base}`,
      aiNotePrefix: "Ghi chú AI:",
      noData: "Chưa có dữ liệu",
    },
    table: {
      watch: "Theo dõi",
      symbol: "Mã",
      exchange: "Sàn",
      industry: "Ngành",
      action: "Thao tác",
      viewDetail: "Chi tiết",
      dnseTrade: "DNSE",
      save: "Luu",
      saved: "Da luu",
    },
  },
  watchlist: {
    title: "Danh sách theo dõi",
    description: "Các mã lưu trên trình duyệt của bạn.",
    empty: "Chưa có mã nào. Vào Thị trường và bấm Lưu để thêm.",
    table: {
      symbol: "Mã",
      exchange: "Sàn",
      industry: "Ngành",
      action: "Thao tác",
      view: "Xem",
      dnseTrade: "DNSE",
      remove: "Xoa",
    },
  },
  symbol: {
    overviewBadge: "TỔNG QUAN MÃ",
    fallbackCompanyName: "Chưa có tên công ty",
    companyId: "Mã công ty",
    exchange: "Sàn",
    industry: "Ngành",
    marketCap: "Vốn hóa",
    issueShare: "Cổ phiếu lưu hành",
    financialIssueShare: "CP theo tỷ lệ tài chính",
    charterCapital: "Vốn điều lệ",
    icbLevel2: "ICB cấp 2",
    icbLevel3: "ICB cấp 3",
    icbLevel4: "ICB cấp 4",
    companyProfile: "Giới thiệu công ty",
    history: "Lịch sử",
    news: "Tin tức",
    noNews: "Chưa có tin tức.",
    readMore: "Đọc thêm",
    priceChart: "Biểu đồ giá",
    chartDataRange: "Dữ liệu",
    chartRange3M: "3 tháng",
    chartRange1Y: "1 năm",
    chartRangeAll: "Toàn bộ",
    chartIntervalLabel: "Chu kỳ nến",
    chartIndicators: "Chỉ báo",
    indicatorSma20: "SMA 20",
    indicatorSma50: "SMA 50",
    indicatorBollinger: "Bollinger",
    indicatorRsi: "RSI 14",
    indicatorMacd: "MACD",
    financialRatioSummary: "Tóm tắt chỉ số tài chính",
    financialRatioByQuarter: "Theo quý",
    financialRatioByYear: "Theo năm",
    financialRatioEmpty: "Chưa có dữ liệu chỉ số tài chính.",
    financialRatioLoading: "Đang tải chỉ số tài chính...",
    aiAnalyze: "Phân tích AI",
    shortAiAnalyze: "Phân tích AI ngắn",
    aiTitle: "Phân tích AI",
    aiLoading: "AI đang phân tích mã này...",
    shortAiLoading: "AI đang tạo bố cục kỹ thuật ngắn...",
    aiEmpty: "Chưa có phân tích AI. Bấm Phân tích AI.",
    shortTitle: "Bố cục kỹ thuật ngắn",
    shortEmpty: "Chưa có bố cục ngắn. Bấm Phân tích AI ngắn.",
    dnseTrade: "Giao dịch DNSE",
    loadFailed: "Không tải được chi tiết mã",
    loadingChart: "Đang tải dữ liệu biểu đồ...",
    completeness: {
      overall: "Tổng thể",
      market: "Thị trường",
      fundamentals: "Cơ bản",
      news: "Tin tức",
      social: "Xã hội",
    },
    bias: "Xu hướng",
    confidence: "Độ tin cậy",
    executiveSummary: "Tóm tắt nhanh",
    marketAnalysis: "Phân tích thị trường",
    fundamentalsAnalysis: "Phân tích cơ bản",
    newsAnalysis: "Phân tích tin tức",
    socialSentimentAnalysis: "Tâm lý xã hội",
    riskMatrix: {
      risk: "Rủi ro",
      probability: "Xác suất",
      impact: "Tác động",
      monitoring: "Theo dõi",
    },
    scenarioBull: "Tăng mạnh",
    scenarioBase: "Trung tính",
    scenarioBear: "Giảm",
    rawShow: "Xem bản gốc",
    rawHide: "Ẩn bản gốc",
    shortBuy: "Điểm mua",
    shortCondition: "Điều kiện",
    shortSell: "Điểm bán",
    shortStop: "Cắt lỗ",
    modalClose: "Đóng",
  },
  operations: {
    pageTitle: "Giám sát vận hành",
    pageIntro:
      "Tổng hợp tín hiệu, lệnh, vị thế, thanh toán bù trừ, tóm tắt giám sát và sự kiện rủi ro từ API trading core và signal engine.",
    loadFailed: "Không tải được dữ liệu.",
    globalLoading: "Đang tải dữ liệu...",
    refresh: "Làm mới",
    refreshing: "Đang làm mới...",
    accountMode: "Chế độ tài khoản",
    tabDemo: "Demo",
    tabReal: "Thật",
    emptyBlock: "Chưa có dữ liệu tóm tắt.",
    sectionSummary: "Tóm tắt giám sát",
    sectionScheduler: "Scheduler tự động",
    sectionSchedulerHint: "Nguồn: GET /automation/scheduler/status, POST /automation/scheduler/toggle",
    sectionSchedulerHintDemo:
      "Trang thai scheduler la chung cho ca account_mode DEMO (khong phu thuoc session dang chon o dropdown).",
    schedulerEnabled: "Enabled",
    schedulerRunning: "Running",
    schedulerPollSeconds: "Poll (giây)",
    schedulerIntervalMinutes: "Interval (phút)",
    schedulerTimezone: "Timezone",
    schedulerEnable: "Bật scheduler",
    schedulerDisable: "Tắt scheduler",
    schedulerToggling: "Đang cập nhật...",
    sectionSummaryHint: "Nguồn: GET /monitoring/summary?account_mode=REAL|DEMO",
    sectionRealAccount: "Thong tin tai khoan REAL",
    sectionRealAccountHint:
      "Nguon: POST /dnse/account, POST /dnse/sub-accounts, POST /dnse/account-balance (yeu cau DNSE session).",
    sectionDemoAccount: "Thong tin tai khoan DEMO",
    sectionDemoAccountHint: "Nguon: GET /auto-trading/demo/account (X-Demo-Session-Id tu localStorage).",
    sectionDemoAccountHintDemo:
      "Session lay tu dropdown phia tren (dong bo localStorage auto_trading_demo_session_id).",
    demoAccountEmpty: "Chua nhan duoc thong tin tai khoan DEMO.",
    demoAccountSessionMissing: "Khong tim thay demo session. Vao tab Auto Trading DEMO de tao/chon session truoc.",
    demoSessionDropdownLabel: "Chon demo session",
    demoSessionListLoading: "Dang tai danh sach session…",
    demoAccountSessionId: "Demo session",
    demoAccountCash: "So du tien mat",
    demoAccountRealizedPnl: "PnL da thuc hien",
    demoAccountUnrealizedPnl: "PnL tam tinh",
    demoAccountEquity: "Tong gia tri tai khoan",
    demoAccountHoldingsTitle: "Danh muc co phieu dang nam giu",
    demoAccountOpenedAt: "Mo vi the luc",
    demoAccountNoHoldings: "Tai khoan demo hien chua nam giu ma co phieu nao.",
    realAccountNeedSession: "Chua co DNSE session. Dang nhap DNSE o tab Auto Trading truoc de tai du lieu tai khoan REAL.",
    realAccountEmpty: "Chua nhan duoc thong tin tai khoan REAL.",
    realAccountSession: "Trang thai session DNSE",
    realAccountSessionActive: "Da dang nhap",
    realAccountSessionMissing: "Chua dang nhap",
    realAccountSubAccount: "Sub-account dang dung",
    realAccountAccountRows: "Ban ghi account",
    realAccountSubRows: "Ban ghi sub-account",
    realAccountBalanceRows: "Ban ghi account-balance",
    realAccountProfileTitle: "Ho so tai khoan",
    realAccountName: "Ten chu tai khoan",
    realAccountNumber: "So tai khoan",
    realAccountEmail: "Email",
    realAccountPhone: "So dien thoai",
    realAccountBalanceTitle: "So du va tai san",
    realAccountCash: "So du tien mat",
    realAccountNetAsset: "Tai san rong",
    realAccountWithdrawable: "Tien co the rut",
    summaryAccount: "Tài khoản",
    summaryGenerated: "Cập nhật",
    summarySymbols: "Số mã",
    summaryTotalQty: "Tổng KL",
    summaryAvailable: "KL khả dụng",
    summaryPending: "KL chờ thanh toán",
    summaryRisk7d: "Sự kiện rủi ro 7 ngày",
    summaryOrdersByStatus: "Lệnh theo trạng thái",
    summaryNoOrders: "Chưa có lệnh ghi nhận.",
    summaryKpiTitle: "Chỉ số vận hành (PnL / exposure / drawdown)",
    summaryBotStatus: "Trạng thái bot",
    summaryKillSwitch: "Kill switch",
    summaryValuationMethod: "Phương pháp định giá",
    summaryValuationNotes: "Ghi chú định giá",
    summaryExposureCost: "Exposure (giá vốn BQ)",
    summaryExposureMarket: "Exposure (MTM)",
    summaryUnrealizedPnl: "PnL chưa thực hiện (MTM)",
    summaryWinRate: "Tỷ lệ thắng (experience)",
    summaryRealizedPnlExp: "PnL đã ghi (experience, tổng)",
    summaryDrawdown: "Drawdown proxy",
    summaryKpiScope: "Phạm vi số liệu",
    summaryKpiError: "Lỗi tính KPI",
    summaryAiRuntimeTitle: "Runtime AI Claude",
    summaryAiRuntimeScoring: "Signal scoring",
    summaryAiRuntimeExperience: "Experience analysis",
    summaryAiCache: "Cache hit/miss",
    summaryAiRequests: "Request success/failure",
    summaryAiCooldown: "Cooldown trigger/reject",
    summaryAiRemaining: "Cooldown còn lại (giây)",
    sectionRisk: "Sự kiện rủi ro",
    sectionRiskHint: "Nguồn: GET /risk/events",
    sectionRiskHintDemo:
      "Theo demo session dang chon: du lieu duoc map tu trade history cua GET /auto-trading/demo/account.",
    riskEmpty: "Chưa có sự kiện rủi ro.",
    sectionSignals: "Tín hiệu",
    sectionSignalsHint: "Nguồn: GET /signals",
    sectionSignalsHintDemo:
      "Theo demo session dang chon: du lieu duoc map tu trade history cua GET /auto-trading/demo/account.",
    signalsEmpty: "Chưa có tín hiệu.",
    sectionOrders: "Lệnh",
    sectionOrdersHint: "Nguồn: GET /orders",
    sectionOrdersHintDemo:
      "Theo demo session (header X-Demo-Session-Id): lịch sử giao dịch từ GET /auto-trading/demo/account.",
    ordersEmpty: "Chưa có lệnh.",
    sectionPositions: "Vị thế",
    sectionPositionsHint: "Nguồn: GET /positions",
    sectionPositionsHintDemo: "Theo demo session: vị thế từ GET /auto-trading/demo/account (không gộp mọi session).",
    positionsEmpty: "Chưa có vị thế.",
    sectionSettlement: "Thanh toán bù trừ (theo lot)",
    sectionSettlementHint: "Nguồn: GET /positions/settlement",
    sectionSettlementHintDemo:
      "Demo sandbox không dùng bảng T+2 của trading core; xem vị thế và lịch sử giao dịch ở các mục trên.",
    settlementEmpty: "Chưa có lot nào.",
    settlementEmptyDemo: "Không áp dụng cho demo session (không có lot T+2 từ trading core).",
    sectionSummaryHintDemo:
      "Tom tat theo demo session dang chon, tinh tu GET /auto-trading/demo/account (khong dung monitoring global).",
    colTime: "Thời điểm",
    colStrategy: "Chiến lược",
    colSymbol: "Mã",
    colAction: "Hành động",
    colConfidence: "Độ tin cậy",
    colStatus: "Trạng thái",
    colReason: "Lý do",
    colSide: "Chiều",
    colQty: "KL",
    colPrice: "Giá",
    colTotalQty: "Tổng KL",
    colAvailableQty: "KL khả dụng",
    colPendingQty: "KL chờ",
    colAvgPrice: "Giá BQ",
    colBuyDate: "Ngày mua",
    colSettleDate: "Ngày T+",
    colEventType: "Loại sự kiện",
    colPayload: "Payload",
  },
  autoTrading: {
    pageTitle: "Auto Trading",
    pageIntro:
      "Chế độ thật: đăng nhập DNSE và tra cứu mã. Chế độ demo: mô phỏng sổ lệnh cục bộ, ghi nhận bài học khi đóng lệnh lỗ.",
    tabReal: "Real",
    tabDemo: "Demo",
    dnseTitle: "Đăng nhập DNSE",
    dnseHint:
      "Dùng username/password gọi POST /dnse/auth/login hoặc dán JWT (access_token) đã có để lưu vào session.",
    tokenPasteLabel: "JWT (access_token) thủ công",
    tokenPastePlaceholder: "Dán token...",
    tokenApply: "Lưu token vào phiên",
    tokenMissing: "Nhập token trước khi lưu.",
    accountProbeOk: (acc: number, sub: number, nums: number) =>
      `Đã gọi API tài khoản: ${acc} bản ghi tổng quan, ${sub} sub-account, ${nums} số tài khoản phụ rút gọn.`,
    accountProbeFailed: "Không kiểm tra được tài khoản DNSE.",
    searchTitle: "Tra cứu mã",
    searchDescription: "Lọc theo ticker trên danh sách niêm yết (backend listing), kèm giá đóng phiên gần nhất nếu tải được.",
    searchPlaceholder: "Nhập mã, ví dụ FPT",
    searchHintEmpty: "Nhập ký tự để lọc mã.",
    searchNoResults: "Không có mã khớp.",
    searchLoadingQuotes: "Đang tải giá...",
    searchResultsCount: (n: number) => `Hiển thị ${n} mã (tối đa 24).`,
    searchQuotePartialFail: "Một số mã không tải được giá.",
    symbolsLoading: "Đang tải danh sách mã...",
    symbolsLoadFailed: "Không tải được danh sách mã.",
    colPrice: "Giá gần nhất",
    colChange: "Thay đổi %",
    viewOverview: "Tóm tắt công ty",
    overviewTitle: (code: string) => `Tóm tắt: ${code}`,
    overviewLoading: "Đang tải tóm tắt...",
    overviewEmpty: "Không có dữ liệu tổng quan cho mã này.",
    overviewFailed: "Không tải được tổng quan.",
    companyName: "Tên công ty",
    clearSelection: "Bỏ chọn",
    demoBalanceTitle: "Số dư demo (VND)",
    demoBalanceHint: "Khởi tạo 100.000.000 VND cho mỗi phiên demo, dữ liệu được lưu DB theo session.",
    demoNewSession: "New Demo",
    demoNewSessionCreating: "Đang tạo phiên mới...",
    demoNewSessionCreated: "Đã tạo phiên demo mới.",
    demoSessionListLabel: "Chọn phiên Demo",
    demoSessionListLoading: "Đang tải danh sách phiên...",
    demoTradeTitle: "Lệnh mô phỏng",
    demoTradeHint:
      "Mua trừ tiền mặt theo khớp giá nhập. Bán chỉ khi đủ khối lượng nắm giữ. Bán lỗ (so với giá vốn bình quân) sẽ gửi POST /experience/analyze với account_mode DEMO.",
    demoSubmit: "Thực hiện lệnh",
    demoSubmitting: "Đang xử lý...",
    demoPositionsTitle: "Vị thế demo",
    demoPositionsEmpty: "Chưa có vị thế.",
    demoOrdersTitle: "Lệnh gần đây",
    demoOrdersEmpty: "Chưa có lệnh.",
    demoLogTitle: "Nhật ký",
    demoLogEmpty: "Chưa có sự kiện.",
    demoInvalidSymbol: "Mã không hợp lệ.",
    demoInvalidQty: "Khối lượng phải là số nguyên dương.",
    demoInvalidPrice: "Giá phải là số dương.",
    demoInsufficientCash: (have: string, need: string) =>
      `Không đủ tiền mặt: đang có ${have} VND, cần ${need} VND.`,
    demoSellOverHold: (sym: string, have: number, need: number) =>
      `Không đủ cổ phiếu để bán ${sym}: đang có ${have}, yêu cầu ${need}.`,
    demoBuyFilled: (sym: string, qty: number, px: string, gross: string) =>
      `Mua ${qty} ${sym} @ ${px} (tổng ${gross} VND).`,
    demoSellFilled: (sym: string, qty: number, px: string, gross: string) =>
      `Bán ${qty} ${sym} @ ${px} (thu ${gross} VND).`,
    demoLossAnalyzePending: "Phát hiện lệnh đóng lỗ, đang gửi phân tích kinh nghiệm...",
    demoLossAnalyzeOk: "Đã ghi nhận kinh nghiệm (POST /experience/analyze).",
    demoLossAnalyzeFail: "Gửi phân tích kinh nghiệm thất bại",
  },
  trade: {
    title: "Giao dịch",
    loadFailed: "Không tải được dữ liệu giao dịch",
    symbol: "Mã",
    loadingData: "Đang tải dữ liệu giao dịch...",
    tabs: {
      overview: "Tổng quan",
      sideStats: "Bên mua/bán",
      foreignTrade: "Ngoại khối",
      propTrade: "Tự doanh",
      metric: "Chỉ số",
      value: "Giá trị",
      noData: "Chưa có dữ liệu.",
      totalVolume: "Tổng khối lượng",
      totalValue: "Tổng giá trị",
      buyVolume: "Khối lượng mua",
      sellVolume: "Khối lượng bán",
    },
  },
  dnse: {
    title: "Giao dich DNSE (API /dnse)",
    hint:
      "Can OTP giao dich (Smart OTP hoac email). User/pass co the de trong neu backend da set DNSE_USERNAME/DNSE_PASSWORD.",
    subAccount: "Sub account (accountNo)",
    symbol: "Ma CP",
    side: "Mua / Ban",
    buy: "Mua",
    sell: "Ban",
    quantity: "Khoi luong",
    price: "Gia",
    orderType: "Loai lenh",
    assetType: "Tai san",
    stock: "Co phieu",
    derivative: "Phai sinh",
    loanPackageOptional: "Goi margin (tuy chon)",
    credentialsSection: "Dang nhap DNSE (tuy chon)",
    credentialsHint: "De trong de dung bien moi truong tren server.",
    usernamePlaceholder: "Ten dang nhap DNSE (vi du: so tai khoan / email)",
    passwordPlaceholder: "Mat khau",
    subAccountPlaceholder: "So tiep thu / accountNo (vi du: 0001000001)",
    loadAccountInfo: "Tai thong tin tai khoan & sub-account",
    loadingAccountInfo: "Dang tai...",
    accountSummaryTitle: "Tai khoan (API /dnse/account)",
    subAccountsSummaryTitle: "Sub-account (API /dnse/sub-accounts)",
    accountBalanceSummaryTitle: "Account balance (API /dnse/account-balance)",
    accountInfoHint:
      "Dung user/pass o tren hoac DNSE_USERNAME/DNSE_PASSWORD tren BE. Sub-account trong trong se tu dien neu API tra ve.",
    sessionHint:
      "Buoc 1: Dang nhap de luu JWT vao session (sessionStorage). Cac goi tiep theo tu dong gui access_token, khong can goi lai /auth/login.",
    sessionActive: "Phien DNSE: da dang nhap (JWT da luu)",
    sessionNone: "Phien DNSE: chua dang nhap",
    sessionLogin: "Dang nhap (auth/login)",
    sessionLoggingIn: "Dang dang nhap...",
    sessionLogout: "Dang xuat phien",
    refreshAccountInfo: "Tai lai thong tin",
    loginNeedCredentials: "Nhap username va password de dang nhap.",
    otp: "OTP giao dich",
    requestEmailOtp: "Gui OTP email",
    sendingOtp: "Dang gui...",
    smartOtp: "Smart OTP (Entrade X)",
    placeOrder: "Dat lenh",
    placing: "Dang dat...",
    subAccountRequired: "Nhap sub account.",
    invalidQuantity: "Khoi luong khong hop le.",
    invalidPrice: "Gia khong hop le.",
    invalidOtp: "Nhap OTP (toi thieu 4 ky tu).",
    placeFailed: "Dat lenh that bai.",
    otpFailed: "Khong gui duoc OTP email.",
  },
  chart: {
    noData: "Chưa có dữ liệu biểu đồ.",
    uptrend: "Xu hướng tăng",
    downtrend: "Xu hướng giảm",
    volumeAxis: "KL",
    open: "Mở",
    high: "Cao",
    low: "Thấp",
    close: "Đóng",
    volume: "KL",
    rsiAxis: "RSI",
    macdAxis: "MACD",
    legendSma20: "SMA 20",
    legendSma50: "SMA 50",
    legendBbUpper: "BB trên",
    legendBbLower: "BB dưới",
    legendMacd: "MACD",
    legendSignal: "Tín hiệu",
    zoomIn: "Phóng to",
    zoomOut: "Thu nhỏ",
    resetView: "Xem toàn bộ",
    panZoomHint: "Kéo để di chuyển · lăn chuột để zoom · đúp chuột reset",
    tradingViewHint: "TradingView Lightweight Charts",
    tradingViewControls:
      "Kéo ngang để xem lịch sử · lăn chuột / chạm hai ngón để zoom · Shift + kéo để di chuyển theo trục thời gian",
  },
} as const;
