export const UI_TEXT = {
  appName: "VNStock FE",
  nav: {
    home: "Home",
    market: "Market",
    watchlist: "Watchlist",
    trade: "Trade",
  },
  home: {
    title: "VNStock Market Dashboard",
    description:
      "Frontend da duoc tao de ket noi truc tiep voi backend API tai BE/vnstock/vnstock/api, bao gom danh sach ma, chi tiet ma, chart va trade.",
    openMarket: "Open Market",
    openTrade: "Open Trade",
  },
  market: {
    title: "Danh sach ma co phieu",
    source: "Nguon du lieu: /vnstock-api/listing/all-symbols",
    loadFailed: "Load market data failed",
    searchPlaceholder: "Search symbol or industry",
    sortAz: "Sort: Symbol A-Z",
    sortZa: "Sort: Symbol Z-A",
    result: (count: number) => `Result: ${count} symbols`,
    showing: (from: number, to: number) => `Showing ${from}-${to}`,
    searching: "Searching...",
    prev: "Prev",
    next: "Next",
    page: (current: number, total: number) => `Page ${current} / ${total}`,
    table: {
      watch: "Watch",
      symbol: "Symbol",
      exchange: "Exchange",
      industry: "Industry",
      action: "Action",
      viewDetail: "View detail",
      dnseTrade: "DNSE",
      save: "Save",
      saved: "Saved",
    },
  },
  watchlist: {
    title: "Watchlist",
    description: "Danh sach ma duoc luu local tren trinh duyet cua ban.",
    empty: "Watchlist is empty. Go to Market and press Save on symbols you want to track.",
    table: {
      symbol: "Symbol",
      exchange: "Exchange",
      industry: "Industry",
      action: "Action",
      view: "View",
      dnseTrade: "DNSE",
      remove: "Remove",
    },
  },
  symbol: {
    fallbackCompanyName: "No company name available",
    companyId: "Company ID",
    exchange: "Exchange",
    industry: "Industry",
    marketCap: "Market Cap",
    issueShare: "Issue Share",
    financialIssueShare: "Financial Ratio Issue Share",
    charterCapital: "Charter Capital",
    icbLevel2: "ICB Level 2",
    icbLevel3: "ICB Level 3",
    icbLevel4: "ICB Level 4",
    companyProfile: "Company Profile",
    history: "History",
    news: "News",
    noNews: "No news available.",
    priceChart: "Price chart",
    openTrade: "Open Trade",
    dnseTrade: "Trade DNSE",
    loadFailed: "Load symbol detail failed",
    loadingChart: "Loading chart data...",
  },
  trade: {
    title: "Trade",
    source: (symbol: string) => `Nguon du lieu: /vnstock-api/trading/trading-stats (symbol: ${symbol})`,
    loadFailed: "Load trading data failed",
    symbol: "Symbol",
    sourcePrefix: "Nguon du lieu: /vnstock-api/trading/trading-stats",
    loadingData: "Loading trade data...",
    tabs: {
      overview: "Overview",
      sideStats: "Side Stats",
      foreignTrade: "Foreign Trade",
      propTrade: "Prop Trade",
      metric: "Metric",
      value: "Value",
      noData: "No data available.",
      totalVolume: "Total Volume",
      totalValue: "Total Value",
      buyVolume: "Buy Volume",
      sellVolume: "Sell Volume",
    },
  },
  dnse: {
    title: "Giao dich DNSE (API /dnse)",
    expand: "Mo form",
    collapse: "Thu gon",
    hint:
      "Can OTP giao dich (Smart OTP hoac email). User/pass co the de trong neu backend da set DNSE_USERNAME/DNSE_PASSWORD.",
    subAccount: "Sub account (accountNo)",
    symbol: "Ma CP",
    side: "Mua / Ban",
    buy: "Mua",
    sell: "Ban",
    quantity: "Khoi luong",
    price: "Gia",
    orderType: "Loai lenh",
    assetType: "Tai san",
    stock: "Co phieu",
    derivative: "Phai sinh",
    loanPackageOptional: "Goi margin (tuy chon)",
    credentialsSection: "Dang nhap DNSE (tuy chon)",
    credentialsHint: "De trong de dung bien moi truong tren server.",
    usernamePlaceholder: "Ten dang nhap DNSE (vi du: so tai khoan / email)",
    passwordPlaceholder: "Mat khau",
    subAccountPlaceholder: "So tiep thu / accountNo (vi du: 0001000001)",
    loadAccountInfo: "Tai thong tin tai khoan & sub-account",
    loadingAccountInfo: "Dang tai...",
    accountSummaryTitle: "Tai khoan (API /dnse/account)",
    subAccountsSummaryTitle: "Sub-account (API /dnse/sub-accounts)",
    accountInfoHint:
      "Dung user/pass o tren hoac DNSE_USERNAME/DNSE_PASSWORD tren BE. Sub-account trong trong se tu dien neu API tra ve.",
    sessionHint:
      "Buoc 1: Dang nhap de luu JWT vao session (sessionStorage). Cac goi tiep theo tu dong gui access_token, khong can goi lai /auth/login.",
    sessionActive: "Phien DNSE: da dang nhap (JWT da luu)",
    sessionNone: "Phien DNSE: chua dang nhap",
    sessionLogin: "Dang nhap (auth/login)",
    sessionLoggingIn: "Dang dang nhap...",
    sessionLogout: "Dang xuat phien",
    loginNeedCredentials: "Nhap username va password de dang nhap.",
    otp: "OTP giao dich",
    requestEmailOtp: "Gui OTP email",
    sendingOtp: "Dang gui...",
    smartOtp: "Smart OTP (Entrade X)",
    placeOrder: "Dat lenh",
    placing: "Dang dat...",
    subAccountRequired: "Nhap sub account.",
    invalidQuantity: "Khoi luong khong hop le.",
    invalidPrice: "Gia khong hop le.",
    invalidOtp: "Nhap OTP (toi thieu 4 ky tu).",
    placeFailed: "Dat lenh that bai.",
    otpFailed: "Khong gui duoc OTP email.",
  },
  chart: {
    noData: "No chart data available.",
  },
} as const;
