export const UI_TEXT = {
  appName: "Stock Analysis",
  nav: {
    home: "Trang chủ",
    market: "Thị trường",
    watchlist: "Theo dõi",
    trade: "Giao dịch",
  },
  home: {
    title: "Bảng điều khiển phân tích cổ phiếu",
    description:
      "Giao diện kết nối backend VNStock: danh sách mã, chi tiết mã, biểu đồ và giao dịch.",
    openMarket: "Mở thị trường",
    openTrade: "Mở giao dịch",
    badge: "SÀN CHỨNG KHOÁN",
    news: {
      badge: "TIN TỨC",
      title: "Tin tức",
      description:
        "Tổng hợp từ RSS và nguồn công khai (theo nhóm: trong nước, thế giới, mạng xã hội).",
      filterAll: "Tất cả",
      filterDomestic: "Trong nước",
      filterWorld: "Thế giới",
      filterSocial: "Mạng xã hội",
      filtersAria: "Lọc danh mục tin",
      refresh: "Làm mới",
      refreshAria: "Làm mới tin, bỏ qua cache server",
      refreshLoading: "Đang làm mới...",
      loading: "Đang tải tin...",
      empty: "Chưa có tin cho bộ lọc này.",
      resultCount: (count: number) => `${count} bài`,
    },
  },
  market: {
    title: "Danh sách mã cổ phiếu",
    loadFailed: "Không tải được dữ liệu thị trường",
    refreshFromServer: "Làm mới",
    refreshFromServerLoading: "Đang làm mới...",
    refreshFromServerFailed: "Không làm mới được danh sách.",
    searchPlaceholder: "Tìm mã hoặc ngành",
    sortAz: "Sắp xếp: Mã A-Z",
    sortZa: "Sắp xếp: Mã Z-A",
    result: (count: number) => `Kết quả: ${count} mã`,
    showing: (from: number, to: number) => `Hiển thị ${from}-${to}`,
    searching: "Đang tìm...",
    prev: "Trước",
    next: "Sau",
    page: (current: number, total: number) => `Trang ${current} / ${total}`,
    exchangeAll: "ALL (Tất cả)",
    vn30ListLoading: "Đang tải danh sách VN30...",
    vn30ListError: "Không tải được danh sách VN30. Vẫn có thể lọc theo sàn HOSE / HNX / UPCOM.",
    scanner: {
      title: "Scanner thanh khoản đột biến bất thường",
      daysLabel: "Số ngày",
      asOfPrefix: "Cập nhật:",
      modeLabel: "Chế độ:",
      modeNormal: "Thường",
      modeAi: "AI",
      scanNow: "Quét",
      scanWithAi: "Quét bằng AI",
      scanning: "Đang quét...",
      scanningMarket: "Đang quét thị trường...",
      riskPrefix: "Rủi ro:",
      spikeLine: (ratio: string, latest: string, base: string) =>
        `Tỷ lệ đột biến: ${ratio}x | KL gần nhất: ${latest} | KL nền: ${base}`,
      aiNotePrefix: "Ghi chú AI:",
      noData: "Chưa có dữ liệu",
    },
    table: {
      watch: "Theo dõi",
      symbol: "Mã",
      exchange: "Sàn",
      industry: "Ngành",
      action: "Thao tác",
      viewDetail: "Chi tiết",
      dnseTrade: "DNSE",
      save: "Luu",
      saved: "Da luu",
    },
  },
  watchlist: {
    title: "Danh sách theo dõi",
    description: "Các mã lưu trên trình duyệt của bạn.",
    empty: "Chưa có mã nào. Vào Thị trường và bấm Lưu để thêm.",
    table: {
      symbol: "Mã",
      exchange: "Sàn",
      industry: "Ngành",
      action: "Thao tác",
      view: "Xem",
      dnseTrade: "DNSE",
      remove: "Xoa",
    },
  },
  symbol: {
    overviewBadge: "TỔNG QUAN MÃ",
    fallbackCompanyName: "Chưa có tên công ty",
    companyId: "Mã công ty",
    exchange: "Sàn",
    industry: "Ngành",
    marketCap: "Vốn hóa",
    issueShare: "Cổ phiếu lưu hành",
    financialIssueShare: "CP theo tỷ lệ tài chính",
    charterCapital: "Vốn điều lệ",
    icbLevel2: "ICB cấp 2",
    icbLevel3: "ICB cấp 3",
    icbLevel4: "ICB cấp 4",
    companyProfile: "Giới thiệu công ty",
    history: "Lịch sử",
    news: "Tin tức",
    noNews: "Chưa có tin tức.",
    readMore: "Đọc thêm",
    priceChart: "Biểu đồ giá",
    chartDataRange: "Dữ liệu",
    chartRange3M: "3 tháng",
    chartRange1Y: "1 năm",
    chartRangeAll: "Toàn bộ",
    chartIntervalLabel: "Chu kỳ nến",
    chartIndicators: "Chỉ báo",
    indicatorSma20: "SMA 20",
    indicatorSma50: "SMA 50",
    indicatorBollinger: "Bollinger",
    indicatorRsi: "RSI 14",
    indicatorMacd: "MACD",
    financialRatioSummary: "Tóm tắt chỉ số tài chính",
    financialRatioByQuarter: "Theo quý",
    financialRatioByYear: "Theo năm",
    financialRatioEmpty: "Chưa có dữ liệu chỉ số tài chính.",
    financialRatioLoading: "Đang tải chỉ số tài chính...",
    aiAnalyze: "Phân tích AI",
    shortAiAnalyze: "Phân tích AI ngắn",
    aiTitle: "Phân tích AI",
    aiLoading: "AI đang phân tích mã này...",
    shortAiLoading: "AI đang tạo bố cục kỹ thuật ngắn...",
    aiEmpty: "Chưa có phân tích AI. Bấm Phân tích AI.",
    shortTitle: "Bố cục kỹ thuật ngắn",
    shortEmpty: "Chưa có bố cục ngắn. Bấm Phân tích AI ngắn.",
    dnseTrade: "Giao dịch DNSE",
    loadFailed: "Không tải được chi tiết mã",
    loadingChart: "Đang tải dữ liệu biểu đồ...",
    completeness: {
      overall: "Tổng thể",
      market: "Thị trường",
      fundamentals: "Cơ bản",
      news: "Tin tức",
      social: "Xã hội",
    },
    bias: "Xu hướng",
    confidence: "Độ tin cậy",
    executiveSummary: "Tóm tắt nhanh",
    marketAnalysis: "Phân tích thị trường",
    fundamentalsAnalysis: "Phân tích cơ bản",
    newsAnalysis: "Phân tích tin tức",
    socialSentimentAnalysis: "Tâm lý xã hội",
    riskMatrix: {
      risk: "Rủi ro",
      probability: "Xác suất",
      impact: "Tác động",
      monitoring: "Theo dõi",
    },
    scenarioBull: "Tăng mạnh",
    scenarioBase: "Trung tính",
    scenarioBear: "Giảm",
    rawShow: "Xem bản gốc",
    rawHide: "Ẩn bản gốc",
    shortBuy: "Điểm mua",
    shortCondition: "Điều kiện",
    shortSell: "Điểm bán",
    shortStop: "Cắt lỗ",
    modalClose: "Đóng",
  },
  trade: {
    title: "Giao dịch",
    loadFailed: "Không tải được dữ liệu giao dịch",
    symbol: "Mã",
    loadingData: "Đang tải dữ liệu giao dịch...",
    tabs: {
      overview: "Tổng quan",
      sideStats: "Bên mua/bán",
      foreignTrade: "Ngoại khối",
      propTrade: "Tự doanh",
      metric: "Chỉ số",
      value: "Giá trị",
      noData: "Chưa có dữ liệu.",
      totalVolume: "Tổng khối lượng",
      totalValue: "Tổng giá trị",
      buyVolume: "Khối lượng mua",
      sellVolume: "Khối lượng bán",
    },
  },
  dnse: {
    title: "Giao dich DNSE (API /dnse)",
    hint:
      "Can OTP giao dich (Smart OTP hoac email). User/pass co the de trong neu backend da set DNSE_USERNAME/DNSE_PASSWORD.",
    subAccount: "Sub account (accountNo)",
    symbol: "Ma CP",
    side: "Mua / Ban",
    buy: "Mua",
    sell: "Ban",
    quantity: "Khoi luong",
    price: "Gia",
    orderType: "Loai lenh",
    assetType: "Tai san",
    stock: "Co phieu",
    derivative: "Phai sinh",
    loanPackageOptional: "Goi margin (tuy chon)",
    credentialsSection: "Dang nhap DNSE (tuy chon)",
    credentialsHint: "De trong de dung bien moi truong tren server.",
    usernamePlaceholder: "Ten dang nhap DNSE (vi du: so tai khoan / email)",
    passwordPlaceholder: "Mat khau",
    subAccountPlaceholder: "So tiep thu / accountNo (vi du: 0001000001)",
    loadAccountInfo: "Tai thong tin tai khoan & sub-account",
    loadingAccountInfo: "Dang tai...",
    accountSummaryTitle: "Tai khoan (API /dnse/account)",
    subAccountsSummaryTitle: "Sub-account (API /dnse/sub-accounts)",
    accountBalanceSummaryTitle: "Account balance (API /dnse/account-balance)",
    accountInfoHint:
      "Dung user/pass o tren hoac DNSE_USERNAME/DNSE_PASSWORD tren BE. Sub-account trong trong se tu dien neu API tra ve.",
    sessionHint:
      "Buoc 1: Dang nhap de luu JWT vao session (sessionStorage). Cac goi tiep theo tu dong gui access_token, khong can goi lai /auth/login.",
    sessionActive: "Phien DNSE: da dang nhap (JWT da luu)",
    sessionNone: "Phien DNSE: chua dang nhap",
    sessionLogin: "Dang nhap (auth/login)",
    sessionLoggingIn: "Dang dang nhap...",
    sessionLogout: "Dang xuat phien",
    refreshAccountInfo: "Tai lai thong tin",
    loginNeedCredentials: "Nhap username va password de dang nhap.",
    otp: "OTP giao dich",
    requestEmailOtp: "Gui OTP email",
    sendingOtp: "Dang gui...",
    smartOtp: "Smart OTP (Entrade X)",
    placeOrder: "Dat lenh",
    placing: "Dang dat...",
    subAccountRequired: "Nhap sub account.",
    invalidQuantity: "Khoi luong khong hop le.",
    invalidPrice: "Gia khong hop le.",
    invalidOtp: "Nhap OTP (toi thieu 4 ky tu).",
    placeFailed: "Dat lenh that bai.",
    otpFailed: "Khong gui duoc OTP email.",
  },
  chart: {
    noData: "Chưa có dữ liệu biểu đồ.",
    uptrend: "Xu hướng tăng",
    downtrend: "Xu hướng giảm",
    volumeAxis: "KL",
    open: "Mở",
    high: "Cao",
    low: "Thấp",
    close: "Đóng",
    volume: "KL",
    rsiAxis: "RSI",
    macdAxis: "MACD",
    legendSma20: "SMA 20",
    legendSma50: "SMA 50",
    legendBbUpper: "BB trên",
    legendBbLower: "BB dưới",
    legendMacd: "MACD",
    legendSignal: "Tín hiệu",
    zoomIn: "Phóng to",
    zoomOut: "Thu nhỏ",
    resetView: "Xem toàn bộ",
    panZoomHint: "Kéo để di chuyển · lăn chuột để zoom · đúp chuột reset",
    tradingViewHint: "TradingView Lightweight Charts",
    tradingViewControls:
      "Kéo ngang để xem lịch sử · lăn chuột / chạm hai ngón để zoom · Shift + kéo để di chuyển theo trục thời gian",
  },
} as const;
